### ISSUE TITLE
Tabs have transparent border

### ISSUE THREAD

**Issue by hharnisc** [webmatze/hyperborder#1]
Nice work! This looks really cool 😃

I noticed when adding another tab, the tab borders are set to transparent.

![screen shot 2016-07-17 at 5 49 35 pm](https://cloud.githubusercontent.com/assets/1388079/16903596/6ac656a6-4c48-11e6-9bdf-e407e9e84a8b.png)

**Comment by webmatze** [comment]
Starting with version **0.1.0** of **hyperborder** it is possible to change the color of the tabs borders in your .hyperterm.js configuration.

I also added a default tabs border color, too.

See the [README](https://github.com/webmatze/hyperborder/blob/master/README.md) for more.
