### ISSUE TITLE
Border doesn't work for newest version of Hyper v. 0.8.2

### ISSUE THREAD

**Issue by shampliu** [webmatze/hyperborder#10]

**Comment by tdreitz** [comment]
Getting this when I install:

![screen shot 2016-10-16 at 11 47 18 pm](https://cloud.githubusercontent.com/assets/8248045/19427790/fe199f68-93fa-11e6-8e55-f3338c221272.png)

**Comment by shampliu** [comment]
I made a PR earlier with some simple changes to fix this @webmatze

**Comment by webmatze** [comment]
I am sorry, I did not had the time to  work on this issue on the weekend. Will review and merge your PR #11 in the next hours.
