### ISSUE TITLE
Add the border around the tabs and Terminal separator

### ISSUE THREAD

**Issue by jackyliang** [webmatze/hyperborder#12]
If I have multiple windows, could we have an option to add the gradient border around the separators and tabs?

Thanks!

**Comment by webmatze** [comment]
I don't know if I understand this correctly... Do you mean you want the gradient border around the tabs when you have multiple documents open?

**Comment by jackyliang** [comment]
Hey! Thanks for replying.

You see how right now the tab separators have a grey border around it?

https://puu.sh/s1Vjj/babf0d7b9f.png

Would be nice to have the gradient there too!

**Comment by Xapphire13** [comment]
That should be doable using the regular CSS config setting no?

**Comment by webmatze** [comment]
This could be possible by creating a theme that uses transparencies for the tab borders. But this should not be done by hyperborder.
We only want to provide the styles for the outer border and leave everything else to other plugins.
So I am closing this now.
