### ISSUE TITLE
Gradient not reaching to the top of the screen?

### ISSUE THREAD

**Issue by lcrossan** [webmatze/hyperborder#14]
hey! this extension is awesome, i'm super excited to use it.

running osx (sierra, 10.12), it looks like the gradient doesn't show up on the tabs at the top.

screenshot of what's happening:
http://imgur.com/fVf50Kb

and here's my .hyperterm.js:

```
module.exports = {
  config: {
    hyperBorder : {
      borderColors: ['#5BCEFA', '#F5A9B8', '#FFFFFF', '#F5A9B8', '#5BCEFA'],
      borderWidth: '10px'
    },

    fontSize: 16,

    fontFamily: 'Menlo, "DejaVu Sans Mono", "Lucida Console", monospace',

    cursorColor: 'rgba(248,28,229,0.75)',

    cursorShape: 'BEAM',

    foregroundColor: '#ddd',

    backgroundColor: '#222',

    borderColor: '#222',

    css: '',

    termCSS: '',

    padding: '12px 14px',

    colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff'
    },

    shell: '',

    windowSize: [1000, 650]
  },

  plugins: [
    "hypercwd", "hyperborder", "hyperterm-title",
    "hyperterm-tab-icons", "hyperterm-paste"
  ],
  localPlugins: []
};
```

it's very possible that i'm configuring this wrong and don't know it -- if that's true i'll be pretty happy honestly. couldn't find much with a google, so i figured i'd ask y'all.

thanks!

**Comment by webmatze** [comment]
Thank you for posting your issue.

If I use your configuration I do not get the same behaviour as in your screenshot.

Here is mine:
<img width="898" alt="screenshot 2016-11-08 13 32 03" src="https://cloud.githubusercontent.com/assets/32392/20099250/d6e8b5d6-a5b7-11e6-9e65-8877dd399de3.png">

I am using **hyper** version 0.8.3 – what version are you using? It looks like you are still using the older **hyperterm** version which is not supported anymore. (They changed the name and added lots of changes)

You can get a new version here: https://github.com/zeit/hyper/releases

**Comment by lcrossan** [comment]
hah. did not know there was a new version. thanks so much -- that fixed it. :)
