### ISSUE TITLE
Show different border if app doesnt have the focus?

### ISSUE THREAD

**Issue by bradparks** [webmatze/hyperborder#15]
Cool plugin! I'd love it if there was an easy way to show the border one way when the app has focus, and another way if it didnt.... Is this just css or is there something more that needs to be done?

**Comment by webmatze** [comment]
Good idea.

It should be possible to hook into the `focus` and `blur` events to change the appearance of the border.
But that could mean that we need to make some major changes to the architecture of this plugin.

Feel free to contribute to **hyperborder** and create a pull request. I can investigate this if I find some time, too.

**Comment by Xapphire13** [comment]
@webmatze, this is now closed right?

**Comment by webmatze** [comment]
Right! I will close this issue now. Thank you @Xapphire13
