### ISSUE TITLE
Black border when using any theme

### ISSUE THREAD

**Issue by bnb** [webmatze/hyperborder#2]
Hello!

LOVE Hyperborder. I've finally got plugins working in Hyperterm, so I added a theme and Hyperborder. When I have any theme in addition to Hyperborder, Hyperborder adds a black outline on the terminal: 

<img width="826" alt="screen shot 2016-07-18 at 8 53 00 am" src="https://cloud.githubusercontent.com/assets/502396/16915358/140c7124-4cc5-11e6-8cce-28e26b3f2a5c.png">

Could this be solved by making the black an RGBA color? e.g. `rgba(0,0,0,0)`?

**Comment by webmatze** [comment]
Yes I had the same problem.
I am already working on this. A fix will come later today.

**Comment by bnb** [comment]
Thanks 👍

**Comment by webmatze** [comment]
I published a new version of the plugin.
But there is still a problem if you do not add **hyperborder** as the last item to `plugins: []` in the configuration.

**Comment by magano** [comment]
I'm still having this issue even tho I placed it last
