### ISSUE TITLE
Broken on 1.2!

### ISSUE THREAD

**Issue by jhanstra** [webmatze/hyperborder#20]
Border goes rogue in Hyper 1.2...
![image](https://cloud.githubusercontent.com/assets/1919535/23004096/c8c25eb8-f3c2-11e6-8033-bb3ae7fc22cf.png)

**Comment by ethanmay** [comment]
Adding `background-color: ${config.backgroundColor || '#000'};` to line 46 of index.js will fix it until owner has time to debug.

**Comment by webmatze** [comment]
Thanks for the report.

It looks like you set a transparent background in your `.hyper.js` configuration or another extension is overwriting that value.

Your configuration should look something like this:
```
module.exports = {
  config: {
    ...
    backgroundColor: '#000'
    ...
  }
}
```

I am using version 1.2.1 of hyper and it is working as expected.

**Comment by ethanmay** [comment]
It was broken in 1.2, but 1.2.1 fixed the CSS issues that were happening. All good now!
