### ISSUE TITLE
Background is now gradient

### ISSUE THREAD

**Issue by sbcpdjacobus** [webmatze/hyperborder#25]
After v1.4.0 update the entire background has now become gradient. 

<img width="2560" alt="screen shot 2017-08-30 at 2 26 59 pm 2" src="https://user-images.githubusercontent.com/13050106/29888973-a083f5ac-8d90-11e7-8c0d-665827d0dac4.png">

**Comment by hyphaene** [comment]
Same here.

**Comment by michaelfriedman** [comment]
Ditto, running High Sierra beta.

**Comment by michaelfriedman** [comment]
This is fixed in Hyper 1.4.2.

**Comment by sbcpdjacobus** [comment]
Confirmed, this is resolved in 1.4.2.

**Comment by webmatze** [comment]
Thank you everyone. Will close this issue now.
