### ISSUE TITLE
JavaScript Error

### ISSUE THREAD

**Issue by jamespgrant3** [webmatze/hyperborder#29]
I am using Hyper v. 1.4.8. An update was pushed tonight and hyper now fails to load when the plugin is enabled. `Cannot read property 'borderColors' of undefined`.

Stack:
<img width="485" alt="screen shot 2017-11-09 at 10 48 48 pm" src="https://user-images.githubusercontent.com/7086761/32642231-d2e31b8e-c5a0-11e7-86f0-b9a71d47a8b2.png">

**Comment by smebberson** [comment]
I get the exact same thing too.

**Comment by Xapphire13** [comment]
That would be my mistake. I added a feature that assumes you have a hyperborder config

**Workaround**
Add this to your `.hyper.js` config file

```js
config: {
    // ...
    hyperBorder: {}
}
```

**Comment by jamespgrant3** [comment]
That works, thanks @Xapphire13.

**Comment by webmatze** [comment]
I merged that fix and published a new patch version of **hyperborder** (0.10.1).
Please update your Hyper plugins.

Thanks everyone for reporting the error. And thanks @Xapphire13 for the quick fix.
