### ISSUE TITLE
themes dont work with this plugin

### ISSUE THREAD

**Issue by kingmomo** [webmatze/hyperborder#38]
I was using hyperbroder as one of the plugins and none of the themes worked for me.
The backgourd would default to black and text color would grey out.

This is what "hyper-one-light" looked like:

![31500012-5567eec8-af34-11e7-8618-0ffa993c1b9c](https://user-images.githubusercontent.com/10886770/33489914-6a1dbd68-d683-11e7-878b-d78981b91aff.png)

Here is my hyper version:

![31500051-77c671a6-af34-11e7-924b-6e348da7081c](https://user-images.githubusercontent.com/10886770/33489818-0849e81e-d683-11e7-8bfa-32f9f0cf5dc3.png)
        -
        Hyper 1.4.8
        Electron 1.7.8
        darwin x64 16.7.0
        node v8.9.1
        npm 5.5.1
        bash_profile is clean

No errors seen when theme is added to .hyper.js/plugins.

Console output showed one warning:
>Unimplemented DEC Private Mode: 1034
>r.VT.setDECMode @ bundle.js:47 

Removing "hyperborder" fixed the issue with theme.

**Comment by kingmomo** [comment]
This is duplicate of https://github.com/webmatze/hyperborder/issues/23

**Comment by webmatze** [comment]
@kingmomo As I already answered in the hyper issue...

I looked into the issue with your *hyper-one-light* theme together with the **hyperborder** plugin.

For **hyperborder** to work correctly it is essential to set a **backgroundColor** in your `.hyper.js` config. So **hyperborder** will use that value to set your background.

When **hyper** generates that configuration for the first time, it always sets the **backgroundColor** to `#000` so it will be **black** by default.

When a theme uses a different background color, then you have to explicitly set your `backgroundColor` value to the color used in that theme to work together with **hyperborder**.

**hyper-one-light** uses `#fafafa`.

So it is not really an error but just the way **hyperborder** works as it uses background gradients and colors to generate the desired effects.

But I am not sure if this solves the problem of this issue, as not everyone here seems to use **hyperborder**.
