### ISSUE TITLE
feature request: Darken on window blur

### ISSUE THREAD

**Issue by BerkeleyTrue** [webmatze/hyperborder#39]
I use the i3 manager and use a border to indicate the active window. Unfortunately this plugin overwrites that feature. Would you be interested in a PR around this?

I'm thinking the border should turn black when the window is blurred.

**Comment by webmatze** [comment]
Hey, thank you for your request.
I am glad to tell you that this behaviour should already be possible by using the `blurredColors` configuration property.

```javascript
module.exports = {
  config: {
    ...
      hyperBorder: {
        borderColors: ['#fc1da7', '#fba506'],
        blurredColors: ['#000000']
      }
    ...
  }
}
```

Take a look at the README.

**Comment by BerkeleyTrue** [comment]
Nice, I don't know why that didn't click with me when I first red it. Thanks.

Happy Coding
