### ISSUE TITLE
When out of focus, hyperborder reverts to default border gradient

### ISSUE THREAD

**Issue by haydencrain** [webmatze/hyperborder#40]
I added custom colours and width as suggested:
`hyperBorder: {
      borderColors: ['#00ffff', '#00bbff'],
      borderWidth: '4px'
    },`

When the window is in focus, the border appears as intended (my custom blue/darkblue gradient):
<img width="1280" alt="screen shot 2018-03-08 at 11 39 13 am" src="https://user-images.githubusercontent.com/21377034/37127016-e7c9f4da-22c7-11e8-8aa3-8a1de7bc258d.png">

However, when tabbed out of Hyper terminal, the border reverts back to the initial purple / orange gradient:
<img width="1280" alt="screen shot 2018-03-08 at 11 39 10 am" src="https://user-images.githubusercontent.com/21377034/37126911-5061052a-22c7-11e8-8262-14c4d408f70e.png">

**Comment by haydencrain** [comment]
Nevermind....... adding `blurredColors: ['#00ffff', '#00bbff']`fixes this. I can't read apparently

**Comment by webmatze** [comment]
Okay, maybe we should use the user-defined `borderColor` values as default `blurredColors` values.

**Comment by webmatze** [comment]
@cs-miller That could be done, but not in an easy way. If you still want this feature, can you create a new issue, please?

**Comment by cs-miller** [comment]
@webmatze I just did it manually in my .hyper.js, so don't worry about it.
```
const randomColor = () =>
  `#${Math.floor(Math.random() * 16777215).toString(16)}`;

const randomColorA = randomColor();
const randomColorB = randomColor();
...
  hyperBorder: {
      borderColors: [randomColorA, randomColorB],
      blurredColors: [randomColorA, randomColorB]
  }
...
```

**Comment by webmatze** [comment]
@cs-miller  great.  And I am about to merge the PR #41 for this issue.
Then it will no longer be necessary to define the `blurredColors` with the same values as `borderColors`, as they will then automatically adopt the same colors from `borderColors`.
But it is nevertheless a good example of the flexibility of Hyper's configuration system. :wink:
