### ISSUE TITLE
Gradient is shown over the whole window.

### ISSUE THREAD

**Issue by DavZZar** [webmatze/hyperborder#42]
OS: Windows 10 64-bit

Hyper: 1.4.8 (stable)
Hyperboarder: 0.11.1

Steps to reproduce: None (install Hyperboarder)

Screenshot:
![2018-03-19 13_53_25-hyper](https://user-images.githubusercontent.com/7673161/37599542-eff4442c-2b7c-11e8-8c34-bc7640e95bb9.png)

**Comment by webmatze** [comment]
I am closing this. It is a problem with the transparent backgroundColor and can be fixed by changing the configuration.
