### ISSUE TITLE
Border corner cut

### ISSUE THREAD

**Issue by oriolmirosa** [webmatze/hyperborder#47]
Thanks so much for fixing hyperborder for hyper 2. It now works fine, but for some reason the corners of the border appear to be cut (see screenshot):

![image](https://user-images.githubusercontent.com/6955013/39002200-057921da-43c6-11e8-8091-03a809bfacfd.png)

I'm using hyperborder 1.0.1 with hyper 2.0.0 on MacOS 10.13.4

**Comment by matthew-black** [comment]
Samesies.

**Comment by matthew-black** [comment]
This was actually a super easy fix:
https://github.com/webmatze/hyperborder/pull/48

(Assuming this is the desired default behavior.)

**Comment by Arttse** [comment]
If #46 will be merged, you will be able to change `border-radius` settings (inner and outer).

**Comment by matthew-black** [comment]
Independently of each other?

**Comment by Arttse** [comment]
@matthew-black yes, `borderRadiusInner` for inner and `borderRadiusOuter` for outer. I think you can set `borderRadiusOuter: '0'` to solve this issue.

**Comment by matthew-black** [comment]
Nice. I'll close my pull request. What you pushed up is definitely a feature I'd like to see :)

**Comment by matthew-black** [comment]
@oriolmirosa For a quick fix, you can just make this modification: 
https://d.pr/i/JvEv68
to the index.js file found at:
```
.hyper_plugins/node_modules/hyperborder/
```

**Comment by webmatze** [comment]
@Arttse Thanks for the PR. I will test it today. :+1: 
@matthew-black  maybe `0` should be the default value and if configured it will be overwritten by the changes @Arttse did.
