### ISSUE TITLE
Hyper-3.0.0 canary 8

### ISSUE THREAD

**Issue by willstocks-tech** [webmatze/hyperborder#54]
Hello! 
I just downloaded and installed hyperborder for my Win 10 install of Hyper and have noticed that if you set a border-radius, you'll still see a little of the (default) black square poking over the edges of the border in the corners:
![image](https://user-images.githubusercontent.com/43744514/55782962-4aa5e300-5aa5-11e9-907f-95757a7e7a9e.png)

Is there anything that can be done about this?

**Comment by webmatze** [comment]
Hey @willstocks-tech I think that problem is specific to electron apps (which hyper is based on) under Windows. The round electron windows with transparent background is only possible under MacOS.

Also see this issue for hyper: https://github.com/zeit/hyper/issues/3074

**Comment by willstocks-tech** [comment]
Thanks @webmatze - I assumed that this would be the case, but just wanted to check 😊

**Comment by jcklpe** [comment]
@willstocks-tech You've got it working on Win10 on Canary 8? I've got the same set up but for some reason my borders aren't working. Any clue why? This is a link to my hyper settings: https://github.com/jcklpe/Configs/blob/master/hyper-js/.hyper.js

**Comment by willstocks-tech** [comment]
Yep, I have indeed. It took a little fiddling though... my config file: https://gist.github.com/willstocks-tech/d534245ba7cf3ce8e5f09ec3022e5d46 - I had to move the options right up to the top for some reason

**Comment by jcklpe** [comment]
@willstocks-tech Bingo! Thanks that got it working :)

**Comment by marmelin** [comment]
> @jcklpe Yep, I have indeed. It took a little fiddling though... my config file: https://gist.github.com/willstocks-tech/d534245ba7cf3ce8e5f09ec3022e5d46 - I had to move the options right up to the top for some reason

can you please show some lines of code, because gist is not reachable anymore?
You mean like this: 
```
// Future versions of Hyper may add additional config options,
// which will not automatically be merged into this file.
// See https://hyper.is#cfg for all currently supported options.

module.exports = {
  config: {
 hyperBorder: {
        borderColors: ['#003399', '#0066ff'],
        borderWidth: '3px',
        borderRadiusOuter: '5px',
        borderRadiusInner: '5px',
        adminBorderColors: ['#ff0000','#ffcc66'],
        blurredAdminColors: ['#ffff99','#ff9966'],
        blurredColors: ['#888888', '#eeeeee'],
      },
    // choose either `'stable'` for receiving highly polished,
    // or `'canary'` for less polished but more frequent updates
    updateChannel: 'canary',
...
```
The very first config option under "config:{"?

**Comment by willstocks** [comment]
Try
https://gist.github.com/willstocks/d534245ba7cf3ce8e5f09ec3022e5d46

I changed my GH username

I don’t know if this still works though, as I don’t actively use Hyper
anymore

**Comment by marmelin** [comment]
@willstocks thx for new link . I checked with your config accordingly, but unfortunately there is no change . 

Do you have an available Hyper installation, with which you can try this out?

**Comment by willstocks** [comment]
I can potentially reinstall... I haven’t used Hyper since around the time
of logging those, however, so no idea if there have been more recent
changes with which this config is no longer compatible!
