### ISSUE TITLE
Horizontal and vertical scroll bars appear

### ISSUE THREAD

**Issue by jcalonso** [webmatze/hyperborder#6]
I'm getting horizontal and vertical scrollbars when activating this plugin:

https://cl.ly/0p1n3x1S2H45

**Comment by webmatze** [comment]
Thank you for your report. Do you have any other plugins activated? Can you give me the list?

**Comment by jcalonso** [comment]
Sure,

```
  plugins: [
    "hyperpower",
    "hyperline",
    "hyperterm-tab-icons",
    "hyperterm-materialshell",
    "hyperlinks",
    "hypertheme",
    "hyperterm-close-on-left",
    "hyperborder"
[
```

**Comment by webmatze** [comment]
Okay, that's strange. I installed all the same plugins in the same order but I do not get the scroll bars.

<img width="896" alt="screenshot 2016-09-09 11 12 46" src="https://cloud.githubusercontent.com/assets/32392/18382032/8e657ab8-767f-11e6-87be-55d0de0361c0.png">

Do you have any special configurations in your `.hyperterm.js`?

**Comment by ragozin-n** [comment]
Same issue.
I think it happened when i type «reset» command in bash.

**Comment by webmatze** [comment]
Does anyone still have this problem with the latest version of **hyper**? 
If not I am going to close this issue.

**Comment by jcalonso** [comment]
Still happening on 0.8.3

**Comment by Neko250** [comment]
Hyper Version: `1.0.0`
OS: `Windows 10`
OS Version: `1607 (OS Build 14393.479)`

![scroll-bars](http://i.imgur.com/S125ots.png)

**Comment by arrayout** [comment]
I've the same issue on OSX (10.11.6). 
Hyper version 1.0.0.

**Comment by Neko250** [comment]
@webmatze if you use macOS, try navigating to `System Preferences` > `General` > `Show scroll bars` and set that setting to `Always`. This reproduces the issue.

Confirmed also on:
OS: `macOS Sierra 10.12.1`.
Hyper: `1.0.0.1303`.

![scrolling-hell](https://i.imgur.com/MNtd8U3.png)

**Comment by webmatze** [comment]
@Neko250 Thank you for this tip. I had a hard time reproducing this bug. 👍

**Comment by webmatze** [comment]
I just published version **0.9.2** of hyperborder.
Can anyone confirm, that this fixes the scrollbars problem?

https://www.npmjs.com/package/hyperborder

**Comment by arrayout** [comment]
Yes, now it's work for me.

**Comment by Neko250** [comment]
Working fine now ! 👍

**Comment by webmatze** [comment]
Thank you all for helping me with this issue. :grinning:
