### ISSUE TITLE
Hyperborder broken when using a translucent background

### ISSUE THREAD

**Issue by KhushrajRathod** [webmatze/hyperborder#73]
![Screenshot 2020-09-03 at 7 23 40 PM](https://user-images.githubusercontent.com/44947946/92124110-e6e42e80-edec-11ea-9a64-894ec84ee40a.png)

Hi,
From what I understand hyperborder displays an extra background instead of a border which creates an issue when you have a translucent background

**Comment by webmatze** [comment]
Yes, that is the way the border works at the moment.

But if you want transparancy you can use the https://github.com/lucleray/hyper-opacity plugin. Which allows you to make the whole window transparent.

<img width="756" alt="Bildschirmfoto 2021-03-24 um 22 04 31" src="https://user-images.githubusercontent.com/32392/112383060-ef4e7900-8cec-11eb-980e-edbec8144a2e.png">

**Comment by KhushrajRathod** [comment]
Alright, thanks -- Although that doesn't really work for me, I have the apple-style background blur, not just opacity

**Comment by mayurankv** [comment]
I agree, I don't think this is solved. You can use Transparency and this plugin but not Vibrancy and this plugin. Would be great to be able to choose!
