### ISSUE TITLE
Stop working after Hyper 3.1.5

### ISSUE THREAD

**Issue by EliasGcf** [webmatze/hyperborder#82]
After [Hyper v3.1.5](https://github.com/vercel/hyper/releases/tag/v3.1.5) this plugin stop working.

I am assuming it is because of this PR: https://github.com/vercel/hyper/pull/6128

This is the log in Hyper console.

![image](https://user-images.githubusercontent.com/50633599/148950362-92c9d10b-2524-4c51-9813-519e709d892f.png)

**Comment by birobirobiro** [comment]
Stopped working here too

![image](https://user-images.githubusercontent.com/22185823/148951922-3aac4912-e0ab-40da-92d2-4223866e624c.png)

> After [Hyper v3.1.5](https://github.com/vercel/hyper/releases/tag/v3.1.5) this plugin stop working.
> 
> I am assuming it is because of this PR: [vercel/hyper#6128](https://github.com/vercel/hyper/pull/6128)
> 
> This is the log in Hyper console.
> 
> ![image](https://user-images.githubusercontent.com/50633599/148950362-92c9d10b-2524-4c51-9813-519e709d892f.png)

**Comment by webmatze** [comment]
Thanks for reporting the problem. I'll have a look.

**Comment by webmatze** [comment]
Okay, I just published version **1.3.0** of hyperborder.

It should fix the problems. @EliasGcf would be great if you could test it.

**Comment by EliasGcf** [comment]
Thanks @webmatze, now it is working.

![image](https://user-images.githubusercontent.com/50633599/149035705-c030e3fd-7a3a-48b0-afec-e23dc6a9f146.png)
