### ISSUE TITLE
Plugin failed to load: ENOENT yallist.json

### ISSUE THREAD

**Issue by LostInCompilation** [webmatze/hyperborder#85]
**Issue**
I installed hyper-border but when starting hyper I get the following error message:
<img width="366" alt="Screenshot 2022-06-21 um 04 23 55" src="https://user-images.githubusercontent.com/12819635/174703442-d17dc6b7-64e0-4698-8bd9-b2e5d23e6d26.png">

**This is my hyper.js configuration**
```
module.exports = {
// ...
             config: {
                          hyperBorder: {
                                      borderWidth: '3px',
                                      animate: false,
                           },
            },
            plugins: ["hyperborder"],
// ...
};
```

**Platform info**
Hyper version: 3.2.3 stable
OS: macOS 12.4
Apple Silicon

**Comment by StefanusChristian** [comment]
Sorry if my question is out of context from this issue, does `hyperborder` still active for `hyper.js`? 
I'd notice `hyperborder` is no longer on the plugin list for hyper, and when I'm checking the `About Hyper`, the plugin isn't listed there.
<img width="265" alt="Screen Shot 2022-09-09 at 3 30 52 PM" src="https://user-images.githubusercontent.com/25154563/189307462-9f31b74a-46f8-4d77-ac82-c7f4e0aaa210.png">

**Comment by webmatze** [comment]
Hi @StefanusChristian , as far as I know, hyperborder should still work with Hyper 3.3.0

Here my configuration:
![Bildschirmfoto 2022-09-09 um 11 39 26](https://user-images.githubusercontent.com/32392/189321293-91f1a0e3-28e2-49db-9fbf-23c4e86da37b.png)

Maybe you can try installing hyperborder without any other plugin and look if it works. Than you could try adding the other plugins one by one to see if it is one of them that does not work together with hyperborder anymore.

**Comment by LostInCompilation** [comment]
Hyperborder is completely incompatible with any plugin that enables transparency for me. I tried hyper-opacity, hyper-transparency and the hyper-material-theme. As soon as I enable transparency, the whole window gets colorized with the border color. I have only hyper-border and hyper-transparency/hyper-opacity enabled.

Is there a solution for this?
Hyper 3.3.0


<img width="938" alt="Screenshot 2022-09-09 at 22 20 36" src="https://user-images.githubusercontent.com/12819635/189436760-bcf2a0a4-7d6b-4eec-b126-ceee1c1a6703.png">

**Comment by webmatze** [comment]
Yes I understand that it is not ideal. I am using hyper-opacity with hyperborder and it just works well.

```javascript
module.exports = {
  config: {
    hyperBorder: {
      borderRadiusOuter: '4px',
      animate: "1s"
    },
    opacity: 0.5,
    plugins: [
      'hyper-opacity',
      'hyperborder'
  ],
...


}
```
![Bildschirmfoto 2022-09-10 um 00 50 07](https://user-images.githubusercontent.com/32392/189455809-6bd90228-80fb-489c-bd72-b83b201cbba6.png)

But any plugin that changes the styling of hyper can collide with other plugins that do the same.

If somebody knows how to do gradient borders without using the whole area of the background, I will be glad to hear how it is done.

**Comment by LostInCompilation** [comment]
Yes the opacity plugin is working. However I would like to use vibrance (a blur additionally to opacity). Every plugin I tested did not work with hyper border. Do you have a suggestion?

**Comment by webmatze** [comment]
I did some research and I think I found a possible solution to the problem using SVG and CSS stroke:
https://codepen.io/webmatze/pen/QWrNPNM

But I have to do some tests if this also works with animations and so.

**Comment by LostInCompilation** [comment]
Sounds good, let's hope this will work.
But to cleanup the issue a bit: You can close this issue, hyper-border is working with the current hyper version. I will open a new issue regarding the rendering problem.
