### ISSUE TITLE
border does not surround the entire window

### ISSUE THREAD

**Issue by CsarGomez** [webmatze/hyperborder#86]
i started using hyper but seems like there's an issue, or im doing something wrong

![Screen Shot 2022-07-05 at 2 40 54 PM](https://user-images.githubusercontent.com/5133753/177403403-9d91ff6e-bcd2-4a18-96eb-caebfbb89762.png)

heres the config:
[gist:2f6cb9857b47d1bb27c6f966cf3ca3aa](https://gist.github.com/CsarGomez/2f6cb9857b47d1bb27c6f966cf3ca3aa)

**Comment by webmatze** [comment]
Hey @CsarGomez, this looks to be like a incompatibly between **hyperborder** and the **nord-hyper** plugin.
**nord-hyper** is doing something with the tabs that interferes with the border created by hyperborder.

**Comment by CsarGomez** [comment]
@webmatze 
thanks for taking the time to check.
You'r absolutely right, i change the theme and hyperborder is working as expected.
btw sorry to waste your time on this i will close the issue
