### ISSUE TITLE
Hyperborder issue with transparency and Canvas renderer

### ISSUE THREAD

**Issue by LostInCompilation** [webmatze/hyperborder#87]
_**Issue seperated from https://github.com/webmatze/hyperborder/issues/85#issuecomment-1242425084**_
Hyperborder is completely incompatible with any plugin that enables transparency for me. I tried hyper-vibrance, hyper-transparent, hyper-material-theme and simply setting the alpha value of the background color attribute. As soon as I enable transparency, the whole window gets colorized with the border color. I only have hyper-border and hyper-transparent/hyper-vibrance enabled.

The Canvas renderer is a problem. When enabling Canvas and transparency, the error below happens. With WebGL it works, but then I cannot use transparency. I want to use vibrance, which needs transparency. Hyper-opacity works with WebGL, but not with vibrancy... Man these incompatibilities are a real pain.

**WIP fix**: https://github.com/webmatze/hyperborder/issues/85#issuecomment-1242713581

<img width="938" alt="189436760-bcf2a0a4-7d6b-4eec-b126-ceee1c1a6703" src="https://user-images.githubusercontent.com/12819635/189488558-f82dd952-fbf0-432e-b815-fb5008144e60.png">
<img width="285" alt="189437065-65407e7f-e2a5-43bc-9d2d-e0f739187e6c" src="https://user-images.githubusercontent.com/12819635/189488561-44dbb883-da86-4a6b-ad8c-4e8a7f81178a.png">

**Comment by webmatze** [comment]
Okay, I am making progress.
Look at this 😄 
![Bildschirmfoto 2022-09-11 um 22 03 59](https://user-images.githubusercontent.com/32392/189546834-edacb7a2-8a83-4ad0-ab81-0fd76376be6e.png)

**Comment by LostInCompilation** [comment]
Fire 🔥

**Comment by LostInCompilation** [comment]
Great! Is the update already available? Just click "Update plugins" in Hyper?

**Comment by webmatze** [comment]
I just released version 2.0 of hyperborder! Would be great if you could try it and see if it works for you.

**Comment by LostInCompilation** [comment]
Transparency and vibrancy is working. However the corners seem to have an issue. It also happens with just a transparent background color.
<img width="958" alt="Screenshot 2022-09-17 at 20 28 16" src="https://user-images.githubusercontent.com/12819635/190871527-bc2c5a3d-7cc0-406e-ba2e-71529b5c640f.png">

**Comment by LostInCompilation** [comment]
This is how the corners look when using a thinner border.
<img width="124" alt="Screenshot 2022-09-17 at 23 20 20" src="https://user-images.githubusercontent.com/12819635/190876824-824fe215-2b74-4e41-a2fb-13489c0c2743.png">

**Comment by LostInCompilation** [comment]
Without transparency enabled (via background color) it look fine. Also the border is thicker (image is 3px width, above image with the corner issue is 7px). Somehow the corners of the terminal are more rounded when enabling transparency.
<img width="950" alt="Screenshot 2022-09-17 at 23 22 52" src="https://user-images.githubusercontent.com/12819635/190876885-4f37f0bf-ac20-4497-823d-24ef29706c4f.png">

**Comment by webmatze** [comment]
Thanks for reporting. 

At the moment it looks like we have to fine tune the inner and outer borderRadius.

Try using the defaults be removing `borderWidth`, `borderRadiusInner` and `borderRadiusOuter`.

And the `borderWith` seems to be always half of the defined width. I think the other half is outside of the view.

I will try to fix it.

**Comment by LostInCompilation** [comment]
Without the border attributes, just the animate attribute:
<img width="958" alt="Screenshot 2022-09-18 at 17 02 54" src="https://user-images.githubusercontent.com/12819635/190913830-01150ee7-a16c-4afb-be69-2e2637399d53.png">
