### ISSUE TITLE
hyperterm 0.8.0

### ISSUE THREAD

**Issue by patrickleet** [webmatze/hyperborder#9]
With the update to hyperterm 0.8.0 the gradient now covers the whole terminal, rather than being just a border!

**Comment by webmatze** [comment]
Can you tell me which version of HyperTerm you are using?
I don't seem to have this problem with version 0.7.1 of HyperTerm.

**Comment by patrickleet** [comment]
Yes, its in the issue title - 0.8.0

**Comment by pablopunk** [comment]
Same here. They [released today](https://github.com/zeit/hyper/releases/tag/0.8.0) the version 0.8 and this is what happens when you update it.

<img width="716" alt="screen shot 2016-10-06 at 11 58 56 am" src="https://cloud.githubusercontent.com/assets/4324982/19160088/8e841034-8bbc-11e6-8d9a-150acacccb36.png">

**Comment by webmatze** [comment]
Ah, I am sorry. I thought you meant version 0.8.0 of hyperborder – the version I am currently working on. Sorry for the confusion.

Now I see what you mean.

I will fix this in the next version.

**Comment by pablopunk** [comment]
Ok thank you.

BTW They [just released 0.8.1](https://github.com/zeit/hyper/releases/tag/0.8.1) which changes the name to *hyper app* and adds split panels and transparency.

**Comment by sebinsua** [comment]
I also have this problem. It did give me a good laugh, though. *wow, snazzy*

**Comment by webmatze** [comment]
It's fixed! just update **hyperborder** to version **0.7.1**.

If you still want that full gradient look - just change your `.hyperterm.js` configuration:

```javascript
backgroundColor: 'transparent'
```

Thank you all for reporting this!
