### ISSUE TITLE
Plugin error: Undefined

### ISSUE THREAD

**Issue by mikemand** [webmatze/hyperborder#91]
Hello, I get the following error after installing v2 of your plugin: Plugin error: undefined: Error occurred in `reduceUI`.

Here's a screenshot of the console: 
<img width="912" alt="Screen Shot 2022-09-17 at 3 19 29 PM" src="https://user-images.githubusercontent.com/745184/190876786-66c70c88-8a5c-48a7-b1dc-25e2e86b403a.png">

The TypeError and "Calling execSync" lines are repeated about once per second.

I am running Hyper on an M1 Mac on macOS Monterey (12.4). Let me know what other details you need me to provide, as well as troubleshooting actions you need me to take.

**Comment by LostInCompilation** [comment]
The error is caused by hyperline, not hyperborder. Hyperline has problems with network widgets, which is known. Disable hyperline.

**Comment by mikemand** [comment]
Hi @LostInCompilation, thank you for the reply but that doesn't seem to fix it:

<img width="912" alt="Screen Shot 2022-09-17 at 5 14 21 PM" src="https://user-images.githubusercontent.com/745184/190879344-32b61408-92a7-4962-a09f-5d68be59aaee.png">

Here is my Hyper info:
<img width="372" alt="Screen Shot 2022-09-17 at 5 16 07 PM" src="https://user-images.githubusercontent.com/745184/190879353-d99e65bd-7aa5-4282-895e-cc0377265dce.png">

**Comment by mikemand** [comment]
Adding `animate: {},` to my `hyperBorder` config worked.

**Comment by LostInCompilation** [comment]
Yes the duration error is a different one than you posted before. The duration issue was caused by the _animate_ property, as you found out.
Your first error screenshot was caused by hyperline.

**Comment by mikemand** [comment]
Ah, I see what you mean now. Yes, that specific error was hyperline. Instead of completely disabling the plugin, [you can apparently disable the Network and Spotify options](https://github.com/Hyperline/hyperline/issues/199#issuecomment-905600431).

However, hyperborder was preventing the CLI from working at all because of the `animate` property.

Without `animate`:
<img width="1552" alt="Screen Shot 2022-09-17 at 5 27 07 PM" src="https://user-images.githubusercontent.com/745184/190879503-e85fb6b4-7de1-48d1-bbb5-8f26351cd662.png">

With `animate`:
<img width="1552" alt="Screen Shot 2022-09-17 at 5 27 39 PM" src="https://user-images.githubusercontent.com/745184/190879510-5f10197a-e3b0-4ebc-ad12-b6cd310af946.png">

**Comment by webmatze** [comment]
Hi @mikemand There was a problem with hyperborder when there was no configuration present for `hyperBorder: {}`.

This has been fixed in  the latest patch release . See #93
