### ISSUE TITLE
Border colors default when window not In focus

### ISSUE THREAD

**Issue by kmaustin32** [webmatze/hyperborder#99]
Hi, the issue is that whenever they Hyper window isn't in focus, the borders default back to the pink and yellow. When you click on the window again, the correct colors show again. I didn't see anything in the settings that would account for this, but could be mistaken. Installed on Windows 11, if that makes a difference here.

**Comment by webmatze** [comment]
Hi, there is a feature where you can define different border colors for inactive Hyper windows: `blurredColors `.
Do you have those defined in your configuration?
Take a look at the README for a description of the feature.

**Comment by kmaustin32** [comment]
Yes, I missed that. All is working. Thanks.
